<?php
/**
 * @OA\Schema(
 *     schema="BasicUserData",
 *     type="object",
 *
 *                  @OA\Property(
 *                      property="device",
 *                      type="object",
 *                      @OA\Property(
 *                          property="manufacturer",
 *                          type="string"
 *                      ),
 *                      @OA\Property(
 *                          property="product",
 *                          type="string"
 *                      ),
 *                      @OA\Property(
 *                          property="isMobile",
 *                          type="number"
 *                      ),
 *                      @OA\Property(
 *                          property="memory",
 *                          type="number"
 *                      ),
 *                      @OA\Property(
 *                          property="resolution",
 *                          type="object",
 *                          @OA\Property(
 *                              property="width",
 *                              type="number"
 *                          ),
 *                          @OA\Property(
 *                              property="height",
 *                              type="number"
 *                          ),
 *                      )
 *                  ),
 *                  @OA\Property(
 *                      property="os",
 *                      type="object",
 *                      @OA\Property(
 *                          property="architecture",
 *                          type="string",
 *                      ),
 *                      @OA\Property(
 *                          property="family",
 *                          type="string",
 *                      ),
 *                      @OA\Property(
 *                          property="version",
 *                          type="string",
 *                      ),
 *                  ),
 *                  @OA\Property(
 *                      property="browser",
 *                      type="object",
 *                      @OA\Property(
 *                          property="name",
 *                          type="string",
 *                      ),
 *                      @OA\Property(
 *                          property="version",
 *                          type="string",
 *                      ),
 *                      @OA\Property(
 *                          property="userAgent",
 *                          type="string",
 *                      ),
 *                      @OA\Property(
 *                          property="language",
 *                          type="string",
 *                      ),
 *                  ),
 *                  @OA\Property(
 *                      property="connection",
 *                      type="object",
 *                      @OA\Property(
 *                          property="bandwidth",
 *                          type="number"
 *                      ),
 *                      @OA\Property(
 *                          property="ipAddress",
 *                          type="string"
 *                      ),
 *                      @OA\Property(
 *                          property="effectiveType",
 *                          type="string"
 *                      )
 *                  ),
 *                  @OA\Property(
 *                      property="location",
 *                      type="object",
 *                  ),
 * )
 * @OA\Schema(
 *                  schema="UserData",
 *                  type="object",
 *                  allOf={
 *                      @OA\Schema(
 *                          required={"cookie_id"},
 *                          @OA\Property(property="cookie_id", type="string")
 *                      ),
 *                      @OA\Schema(
 *                          required={"partnerId"},
 *                          @OA\Property(property="partnerId", type="string")
 *                      ),
 *                      @OA\Schema(ref="#/components/schemas/BasicUserData")
 *                  }
 *              )
 * ),
 * @OA\Schema(
 *                  schema="SearchTerm",
 *                  type="object",
 *                  allOf={
 *                      @OA\Schema(
 *                          required={"cookie_id"},
 *                          @OA\Property(property="cookie_id", type="string")
 *                      ),
 *                      @OA\Schema(
 *                          required={"partnerId"},
 *                          @OA\Property(property="partnerId", type="string")
 *                      ),
 *                      @OA\Schema(
 *                          required={"searchTerm"},
 *                          @OA\Property(property="searchTerm", type="string")
 *                      )
 *                  }
 *              )
 * ),
 * @OA\Schema(
 *                  schema="UserRegister",
 *                  type="object",
 *                  @OA\Property(
 *                      property="cookieId",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="partnerId",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="userId",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="birthDate",
 *                      type="string",
 *                      description="yyyy-mm-dd"
 *                  ),
 *                  @OA\Property(
 *                      property="emailDomain",
 *                      type="string",
 *                      description="gmail.com"
 *                  ),
 *                  @OA\Property(
 *                      property="phoneProvider",
 *                      type="string",
 *                      description="20,30,70"
 *                  ),
 *                  @OA\Property(
 *                      property="sex",
 *                      type="string",
 *                      description="male | female"
 *                  ),
 *                  @OA\Property(
 *                      property="realCityName",
 *                      type="string",
 *                      description="User real city name"
 *                  ),
 *                  @OA\Property(
 *                      property="realPostalCode",
 *                      type="string",
 *                      description="User real postal code"
 *                  ),
 *                  required={"cookieId","userId","partnerId"}
 *              )
 * )
 * @OA\Schema(
 *                  schema="PageLoad",
 *                  type="object",
 *                  @OA\Property(
 *                      property="cookieId",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="partnerId",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="toUrl",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="fromUrl",
 *                      type="string",
 *                  ),
 *                  required={"cookieId","partnerId","toUrl"}
 *              )
 * @OA\Schema(
 *                  schema="Interaction",
 *                  type="object",
 *                  @OA\Property(
 *                      property="cookieId",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="partnerId",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="type",
 *                      type="string",
 *                  ),
 *                  @OA\Property(
 *                      property="userId",
 *                      type="string",
 *                      description="required if type is buy"
 *                  ),
 *                  @OA\Property(
 *                      property="items",
 *                      type="array",
 *                      @OA\Items(
 *                          type="object",
 *                          @OA\Property(
 *                              property="id",
 *                              type="string",
 *                          ),
 *                          @OA\Property(
 *                              property="name",
 *                              type="string"
 *                          ),
 *                          @OA\Property(
 *                              property="qty",
 *                              type="number"
 *                          ),
 *                          @OA\Property(
 *                              property="unit_price",
 *                              type="number"
 *                          ),
 *                          required={"id","name"}
 *                      )
 *                  ),
 *                  required={"cookieId","partnerId","type","items"}
 *              )
 *
 * @OA\Parameter(
 *          name="X-Authorization",
 *          in="header",
 *          description="consumer api key",
 *          required=true,
 *          @OA\Schema(type="string")
 *      ),
 */