<?php

namespace Tests\Feature;

use App\User;

abstract class TestCase extends \Tests\TestCase
{
    protected $signedInUser = null;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->signIn();
    }
}
